### ISSUE TITLE
docs.particle.io/firmware 404's

### ISSUE THREAD

**Issue by jenesaisdiq** [particle-iot/docs#71] opened 2015-06-17 03:51 UTC
Would be nicer if URLs of that format redirected to `/photon/firmware` at minimum, and even more ideally to `/core/firmware` or `/photon/firmware` based on the user's previous choice.

**Comment by technobly** [comment] 2015-06-17 05:27
Is this the same as the redirect issue?  You are arriving at `docs.particle.io/firmware` because of an old link `docs.spark.io/firmware` that is redirecting?  I know @joegoggins replaced all old links in the forum posts with the new ones... but are we still wanting to implement a redirect for old external links? i.e., all `docs.spark.io/xxxxx` links will redirect to `docs.particle.io/photon/xxxxx`

**Comment by joegoggins** [comment] 2015-06-17 14:36
Thanks for the ping on this guys. Yea, this does appear to be duplicate of https://github.com/spark/docs/issues/61 , closing, see last comment there for our plan to resolve this.

**Closed as completed by joegoggins** 2015-06-17 14:36 UTC
Labels: enhancement
